version: '3.2'

volumes:
  config:

services:

  kong:
    build:
      context: ./context
    restart: always
    volumes:
      - config:/usr/local/nginx/config.d/cfg
    ports:
      - 80:80
      - 443:443

